package:
  name: q2-long-reads-qc
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel

  run:
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2-feature-classifier {{ qiime2_epoch }}.*
    - nanoplot
    - gzip

  build:
  - setuptools
  - versioningit
  - python {{ python }}

test:
  imports:
    - q2_long_reads_qc
    - qiime2.plugins.long_reads_qc
  commands:
    - pytest --pyargs q2_long_reads_qc

about:
  home: https://github.com/bokulich-lab/q2-long-reads-qc
  license: BSD-3-Clause
  license_family: BSD